# Generated by Django 5.2.4 on 2025-08-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=255)),
                ('first_prize', models.DecimalField(decimal_places=2, help_text='First Prize Amount (₹)', max_digits=10)),
                ('second_prize', models.DecimalField(decimal_places=2, help_text='Second Prize Amount (₹)', max_digits=10)),
                ('third_prize', models.DecimalField(decimal_places=2, help_text='Third Prize Amount (₹)', max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Participation Fee (₹)', max_digits=10)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
