# Generated by Django 5.2.4 on 2025-08-05 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level_start', models.IntegerField(default=1)),
                ('prize_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prize_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prize_3', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='admin_part.competitioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_part.competitioncategory')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_part.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='admin_part.level')),
            ],
        ),
        migrations.DeleteModel(
            name='ParticipantCategory',
        ),
        migrations.AddField(
            model_name='participant',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_part.round'),
        ),
    ]
