# Generated by Django 5.2.4 on 2025-08-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0002_competitioncategory_level_participant_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_seats', models.IntegerField(default=0)),
                ('booked_seats', models.IntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='admin_part.round')),
            ],
        ),
    ]
