# Generated by Django 5.2.4 on 2025-08-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0004_participant_has_paid_participant_total_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='last_registration_date',
            field=models.DateField(blank=True, help_text='Last date for registration for this round', null=True),
        ),
    ]
