# Generated by Django 5.2.4 on 2025-08-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0005_round_last_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='last_registration_date',
        ),
        migrations.AddField(
            model_name='level',
            name='registration_end_date',
            field=models.DateField(blank=True, help_text='Registration end date for this level', null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='registration_start_date',
            field=models.DateField(blank=True, help_text='Registration start date for this level', null=True),
        ),
    ]
