# Generated by Django 5.2.4 on 2025-08-05 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('employee', 'Employee'), ('customer', 'Customer'), ('participant', 'Participant'), ('mentor', 'Mentor'), ('teacher', 'Teacher'), ('school', 'School'), ('college', 'College'), ('vendor', 'Vendor')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('dob_proof', models.FileField(blank=True, null=True, upload_to='participants/dob_proofs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/photos/')),
                ('how_did_you_know', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_board', models.CharField(blank=True, max_length=100, null=True)),
                ('school_location', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
