# Generated by Django 5.2.4 on 2025-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_customuser_role_participantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='edu_doc',
            field=models.FileField(blank=True, null=True, upload_to='participants/education_docs/'),
        ),
    ]
