# Generated by Django 5.2.4 on 2025-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_participantprofile_edu_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
