# Generated by Django 5.2.4 on 2025-08-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_participantprofile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
