# Generated by Django 5.2.4 on 2025-08-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_participantprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
