# Generated by Django 5.2.4 on 2025-08-05 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_participantprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
