# Generated by Django 5.2.4 on 2025-08-08 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_customuser_accepted_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_qualification', models.CharField(choices=[('PhD', 'PhD'), ("Master's Degree", "Master's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ('Diploma', 'Diploma'), ('Other', 'Other')], max_length=50)),
                ('passport_photo', models.ImageField(upload_to='mentors/passport_photos/')),
                ('id_proof', models.FileField(upload_to='mentors/id_proofs/')),
                ('full_address', models.TextField()),
                ('store_or_advisor', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('course_level', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('total_experience_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('work_history', models.TextField(blank=True, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
