# Generated by Django 5.2.4 on 2025-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_mentorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='total_experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
