# Generated by Django 5.2.4 on 2025-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_mentorprofile_total_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('participant', 'Participant'), ('mentor', 'Mentor'), ('teacher', 'Teacher'), ('school', 'School'), ('college', 'College'), ('vendor', 'Vendor')], default='customer', max_length=20),
        ),
    ]
